### ISSUE TITLE
Количество и структура таблиц БД CMS

### ISSUE THREAD

**Issue by fddvoron** [CeVladimirich/cvblog_cms#1]
В CMS чрезмерное количество таблиц в базе. Для хранения постов достаточно двух таблиц:

В первой таблице хранятся сами посты:
CREATE TABLE cmsposts (id int(3) NOT NULL PRIMARY KEY auto_increment, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
topicid INTEGER DEFAULT 0, postflag INTEGER DEFAULT 0, title TEXT, post TEXT) ENGINE=MyISAM DEFAULT CHARSET=utf8;

Вторая таблица название тем (разделов) CMS:
CREATE TABLE cmstopic (id int(3) NOT NULL PRIMARY KEY auto_increment, topic TEXT) ENGINE=MyISAM DEFAULT CHARSET=utf8;

Вывод:
SELECT cmsposts.id, cmsposts.`date`, cmsposts.topicid, cmsposts.postflag, cmsposts.title, cmsposts.post FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id;

Комментарии. Таблица:
CREATE TABLE cmscoments (id int(3) NOT NULL PRIMARY KEY auto_increment, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
postid INTEGER DEFAULT 0, flag INTEGER DEFAULT 0, username TEXT, post TEXT) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by CeVladimirich** [comment]
Спасибо за предложение, буду рассматривать

**Comment by CeVladimirich** [comment]
Открыл для обсуждения

**Comment by KOT4N** [comment]
А че тебе не нравится-то? Так разделение мегапонятное и не требует изучения

**Comment by fddvoron** [comment]
Если потребуется добавить один или несколько разделов, то придется создавать дополнительные таблицы. Это нерационально и в корне неправильно.
Пример для наглядности. 
INSERT INTO cmstopic (id, topic) VALUES (1, 'Обо мне');
INSERT INTO cmstopic (id, topic) VALUES (2, 'Статьи');
INSERT INTO cmstopic (id, topic) VALUES (3, 'Новости');

INSERT INTO cmsposts (topicid, title, post) VALUES (1, 'Обо мне', 'Я такой, родился там, бла-бла-бла');
INSERT INTO cmsposts (topicid, title, post) VALUES (3, 'Новый комп', 'Купил новый комп, бла-бла-бла');

Делаем вывод без условий (базовый запрос):
SELECT cmsposts.id, cmsposts.`date`, cmsposts.topicid, cmsposts.postflag, cmsposts.title, cmsposts.post FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id;

Добавляя условия можно выводить необходимую информацию.
SELECT cmsposts.id, cmsposts.date, cmsposts.postflag, cmsposts.topicid, cmsposts.title, cmsposts.post, cmstopic.topic FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id WHERE cmsposts.topicid = 3
Этим запросом выведем все Новости. И так далее.

Базовый запрос очень длинный, неудобный. Для этого рекомендую использовать Представление (VIEWS) MySQL.

Представление создается очень просто:
CREATE VIEW cmsview AS SELECT cmsposts.id, cmsposts.`date`, cmsposts.topicid, cmsposts.postflag, cmsposts.title, cmsposts.post FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id;

_Представление (VIEW) — объект базы данных, являющийся результатом выполнения запроса к базе данных, определенного с помощью оператора SELECT, в момент обращения к представлению.
Представления иногда называют «виртуальными таблицами». Такое название связано с тем, что представление доступно для пользователя как таблица, но само оно не содержит данных, а извлекает их из таблиц в момент обращения к нему._

С представлением можно работать как с таблицей. **НО, только для вывода информации (SELECT)** 
Использование представления значительно сокращает запрос. Представление хранит наш базовый запрос. 
Теперь чтобы вывести "Новости" 
SELECT * FROM cmsview WHERE cmsposts.topicid = 3
Сортировка тоже работает с представлением.

**Comment by CeVladimirich** [comment]
В принципе, идея хорошая, но есть одна придирка.
CREATE TABLE cmsposts (id int(3) NOT NULL PRIMARY KEY **auto_increment**, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
topicid INTEGER DEFAULT 0, postflag INTEGER DEFAULT 0, title TEXT, post TEXT) ENGINE=MyISAM DEFAULT CHARSET=utf8; и
INSERT INTO cmstopic (**id**, topic) VALUES (**1**, 'Обо мне');
Зачем тогда A_I в этом случае

**Comment by KOT4N** [comment]
А какая разница от количества слов в вопросе к бд? Ооо да, надо чтоб куча всякого барахла было в одной таблице, зато запрос короткий👍
Просто, ну, зачем? Какой резон?

**Comment by CeVladimirich** [comment]
Придирка 2.
Представление создается очень просто:
CREATE VIEW cmsview AS SELECT **cmsposts.id, cmsposts.date, cmsposts.topicid, cmsposts.postflag, cmsposts.title, cmsposts.post** FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id;
А не легче все это заменить на *?

**Comment by CeVladimirich** [comment]
> Какой резон?

Прикол здесь в том, что он предлагает все разделы уместить в одну таблицу для их управления, а информацию из этих разделов в другую. Только вот один момент: надо менять структуру ВСЕГО САЙТА, чтоб это работало нормально и без геммороя с созданием вручную новых страниц

**Comment by fddvoron** [comment]
> Придирка 2.
> 
> > Представление создается очень просто:
> > CREATE VIEW cmsview AS SELECT **cmsposts.id, cmsposts.date, cmsposts.topicid, cmsposts.postflag, cmsposts.title, cmsposts.post** FROM cmsposts INNER JOIN cmstopic ON cmsposts.topicid = cmstopic.id;
> 
> А не легче все это заменить на *?
А зачем нам все поля? Делаем выборку нужных нам полей.

**Comment by fddvoron** [comment]
> А какая разница от количества слов в вопросе к бд? Ооо да, надо чтоб куча всякого барахла было в одной таблице, зато запрос короткий+1 Просто, ну, зачем? Какой резон?

Советую прочитать о нормализации баз данных.

**Comment by fddvoron** [comment]
> надо менять структуру ВСЕГО САЙТА, чтоб это работало нормально и без геммороя с созданием вручную новых страниц

Да, существующий PHP код потребуется **значительно** переписать. 
Но, зато один раз переписав. Не надо будет переписывать его всякий раз когда надо будет добавить раздел. 
Пользовательская часть будет одним index.php, а не N-ым количеством php файлов.

**Comment by CeVladimirich** [comment]
> Да, существующий PHP код потребуется **значительно** переписать.

Раз уж тут идут такие дела, то я создам экспериментальную ветку для таких дел. На этом и остановимся.
