### ISSUE TITLE
ФУТЕРБЛЯТЬ

### ISSUE THREAD

**Issue by KOT4N** [CeVladimirich/cvblog_cms#10]
![IMG_20230128_175435_091](https://user-images.githubusercontent.com/90205154/215273219-f7e024a2-f1fd-4f11-88c1-f3aadea84cb9.jpg)
![IMG_20230128_175429_496](https://user-images.githubusercontent.com/90205154/215273222-0dd2e344-fbb7-437d-84a5-8c258f67cc95.jpg)
СУКА ПРИКРЕПИ

**Comment by KOT4N** [comment]
и у тебя айпи классный, юзни кф шизик

**Comment by KOT4N** [comment]
а ещё "написать письмо" не работает

**Comment by doryan04** [comment]
ты сначала приведи сайт в порядок потом уже про AJAX и React поговорим

**Comment by CeVladimirich** [comment]
1. Cloudflare включен
2. футер прижат, алилуя
3. "Написать письмо" работает

Вопрос считаю закрытым
